services:
  pythonapp:
    build: ./python/
    command: sh -c "sleep 10s ; python3 ./app.py"
    depends_on:
      - mysql

  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: 'Patients'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - '3306:3306'